version: '2.2'
services:
  datanexus:
    build: "data"
    volumes:
     - "/sonatype-work"
    restart: always
  datajenkins:
    build: "data"
    volumes:
     - "/var/jenkins_home"
    restart: always
  dataregistry:
    build: "data"
    volumes:
     - "/tmp/registry"
    restart: always
  jenkins:
    build:
      context: jenkins
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes_from:
      - "datajenkins"
    restart: always
  nexus:
    build: "nexus"
    ports:
      - "8081"
    volumes_from:
      - "datanexus"
    restart: always
  sonarqube:
    build: "sonarqube"
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL:"jdbc:postgresql://sonarqubedb:5432/sonar"
      - SONARQUBE_JDBC_USERNAME:"ci"
      - SONARQUBE_JDBC_PASSWORD:"ci-pass"
    restart: always
  sonarqubedb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER:"ci"
      - POSTGRES_PASSWORD:"ci-pass"
  ldap:
     build: "ldap"
     restart: always
     ports:
      - "389"
  haproxy:
     build: "haproxy"
     ports:
      - "80:80"
      - "8666:8666"
     links:
      - "jenkins:jenkins"
      - "nexus:nexus"
      - "sonarqube:sonarqube"
