version: '3.0'
services:
  db:
    image: mysql:5.7.8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    container_name: petclinic-db-container
  spring:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    container_name: petclinic-app-container
